### ISSUE TITLE
Doesn't Support Threading.

### ISSUE THREAD

**Issue by nonstandarduser** [MScholtes/PS2EXE#130]
I tried several simplified scripts using "Start-ThreadJob" and "foreach-parallel".  Start-Threadjob not recognized as commandlet at all after converting.  Parallel not recognized as parameter in foreach.  You are probably already aware since this is a brand new feature in PShell 7.  Posting this to see whether or not it can be addressed any time soon.  Scripts using "runspacefactory" seem to run just fine after conversion.

**Comment by MScholtes** [comment]
Hello @nonstandarduser,

sorry, there is no way to compile _Powershell Core_ scripts with _PS2EXE_ as stated on the readme page: https://github.com/MScholtes/PS2EXE#powershell-core

And it looks like it will stay this way because there is no compiler delivered with _Powershell Core_.

Greetings

Markus

**Comment by nonstandarduser** [comment]
Alas. Please close the issue.
