### ISSUE TITLE
Fails with: The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,  or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by sharpninja** [MScholtes/PS2EXE#21]
Full output
```ps
PS C:\Users\xxx\choco> invoke-ps2exe C:\Users\xxx\choco\ChocolateyInstallNonAdmin.ps1 C:\Users\xxx\choco\ChocolateyInstallNonAdmin.exe
PS2EXE-GUI v0.5.0.23 by Ingo Karstein, reworked and GUI support by Markus Scholtes

& : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ &'Invoke-ps2exe'  -inputFile C:\Users\xxx\choco\ChocolateyIns ...
+  ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-ps2exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 ```

**Comment by sharpninja** [comment]
That was in PS 7.  With PS 5 it works.

**Comment by MScholtes** [comment]
Hello sharpninja,

there is only limited support for PowerShell Core since it does not include a compiler. I guess you have to start Windows PowerShell (aka PowerShell 5.x) and import the PS2EXE module a second time.
After that the call should work in PowerShell Core too.

Greetings

Markus

**Comment by AndrewSav** [comment]
@MScholtes, can you explain this a bit more? 

a) What compiler does not PowerShell Core include? Please be specific, e.g. [CSharpCodeProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.csharp.csharpcodeprovider?view=dotnet-plat-ext-6.0) is part of .net 6, and presumabily accessible from PowerShell Core.

b) Why loading the module in PS5 makes it work in PS Core?

Thank you in advance!

**Comment by MScholtes** [comment]
Hello @AndrewSav,

I do not know much about _Powershell Core_. Since Microsoft removed important features for Windows specific scripts, _Windows Powershell_ is the better choice for _Windows_ specific scripts. So my earlier statements were pure conjecture.

a) As you see in your own link, the  CSharpCodeProvider is not part of **.Net 6**. It has to be installed additionally with the **.NET Platform Extensions**. I do not know if it can be used in _Powershell Core_ and if _**PS2EXE**_ will recognize it. It would be fine if you try.

b) As stated above, this was my conjecture. In the actual versions of _Powershell Core_ I guess you have to use the _Windows PowerShell Compatibility functionality_ with _Import-Module PS2EXE -UseWindowsPowerShell_ (see here: https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility).

Greetings

Markus

**Comment by kdstephens** [comment]
Works for me with PS 7 using the PowerShell Pro Tools extension in VS Code (https://docs.poshtools.com/powershell-pro-tools-documentation/visual-studio-code/packaging-in-visual-studio-code)
