### ISSUE TITLE
Script with Ukrainian text in code

### ISSUE THREAD

**Issue by foxdgv** [MScholtes/PS2EXE#30]
Good day. My scripts contain Ukrainian language. In the usual version (.ps1) the text in the console is displayed correctly, but in the version (.exe) some Ukrainian letters (і, ї, є) are lost. It displayed as question marks.
If I run my .exe with .cmd using instruction "chcp 1251", the script displays correctly in the console. If I run my .exe directly using the shortcut, the instruction "chcp 1251" can no longer be used, the script text is displayed incorrectly in the console.
My Windows: Windows 10 Enterprise (20H2) x64 Ukrainian.
My Powershell version: 7.1
Please, check how your .exe compiled from .ps1 works with Ukrainian. Thanks.

**Comment by MScholtes** [comment]
Hello foxdgv,

PS2EXE expects the source file in UTF8 encoding (UTF16 works too if source file has a BOM), then the Ukrainian letters should be fine.

You might convert with:
```powershell
Get-Content $SOURCEFILE | Set-Content $SOURCEFILEUTF8 -Encoding UTF8
```

Greetings

Markus

**Comment by foxdgv** [comment]
Good day. Do you seriously think that I do not know that scripts should be written in UTF-8 encoding?
In order to convert the text in UTF-8 you do not need to write programs - Notepad can do this with a simple save.
However, this is not the point. Can you definitely prove that your .exe work correctly with Ukrainian? I think that no.
Try at least this to convert this little script:
write-host "Це повідомлення є тестовим. Воно написане українською мовою.".
When you do this, your program will output text to the screen like this:
Це пов?домлення є тестовим. Воно написане українською мовою.
As you can see, there are no more problems with the letters "є, ї", but there is a problem with the Ukrainian letter "i". This is not an English letter, there is one in the Ukrainian alphabet!
As I already said, if you run the program from .cmd with the instruction "chсp 1251", the letter "і" is displayed correctly. Otherwise, no.
There is no such problem when working with .ps1 files. Also I've tried doing .exe with the -lсid parameter, nothing helps.

**Comment by MScholtes** [comment]
Hello foxgdv,

first a request, please stay friendly.

Now to your issue. When a program compiled with **_PS2EXE_** is started without a surrounding console window (like starting directly out of Explorer), a new cmd.exe window is started. The settings of this window are crucial for the display, you may have to choose a suitable font there.

On my computer your example looks like this, because the console is not using a suitable font and is using codepage 850 per default:

![command window](https://user-images.githubusercontent.com/28536378/101923522-c687f500-3bcf-11eb-8dfc-d44f92cb7856.jpg)

I only got it working with setting the default to a font that is capable of displaying the characters and using the trick here with "chcp 1251": [https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8](url)

Greetings

Markus

**Comment by foxdgv** [comment]
Good day. Didn't I write that when using the .ps1 variant everything works correctly?! Don't need to change any fonts! The console window displays everything without any my settings! What is this solution to the problem?! I will run a console window and set it to each user at home? Or will I explain to each user how to configure some kind of windows there ?!
Didn't I write that adding just one instruction (chcp 1251) to the batch file executed by the cmd-shell solves the problem?!
The problem exists only when using a shortcut to start the program, I cannot shove this instruction (chcp 1251) into it. And this means that your compiler should be able to generate .exe based on code pages correctly, not as he do it now.
Why when I compile a project for another programming language (FoxPro) there are no problems with Ukrainian in the code?!

Of course, I can replace all Ukrainian letters "i" with English "i" in my script before compiling to .exe, but this is not a solution to the problem. What about the Ukrainian data generated by the script in the window?
Also I tried using **set-culture -cultureinfo uk-ua** command, didn't help either.

Sorry for the bad machine translation. I hardly speak spoken English.

**Comment by MScholtes** [comment]
Hello foxdgv,

first of all please: stay objective and leave accusations, I am trying to help you.

second: what I'm trying to explain is that **PS2EXE** can't control the appearance of the console with the wrong char, because **Windows** creates this itself.
For example take this C# code and store it in a file named **test.cs**
```C#
namespace Ukrain
{
	class charsettest
	{
		static void Main()
		{
			System.Console.WriteLine("Це повідомлення є тестовим. Воно написане українською мовою.");
			System.Console.ReadKey();
		}
	}
}
```
Now compile it to an executable with:
```cmd
C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe test.cs
```

Now start the generated **test.exe** with double click in Windows Explorer (or with a shortcut as you do it with your script).
This should produce the same behaviour as your compiled script with the wrong character.

I have two suggestions to remedy your problem:
1. Why don't you use 
```powershell
chcp 1251
```
as the first command in your scipt?

2. Choose a working font in the properties of the shortcut you are using to start the compiled script.

Greetings

Markus

**Comment by foxdgv** [comment]
Why don't you read what I write?

Start over:
1.cmd.exe in Windows 10 works with Ukrainian without problems. No window or font settings. Instruction "chcp 1251" is not required.
2.powershell.exe with .ps1 work with Ukrainian without problems. No window or font settings. Instruction "chcp 1251" is not required.
3. Your .exe, compiled from .ps1, does not work correctly with Ukrainian. It's impossible? But what about the options that are in paragraphs 1 and 2?
4. Your .exe, compiled from .ps1, work with Ukrainian correctly only if you run it from cmd-shell with the "chcp 1251" instruction. But I don't need that! I need to run .exe from a shortcut! Without any window and font settings!

For example: I have a library of functions: tools.ps1. I can execute a command file like this:
pwsh.exe -executionpolicy bypass -file %windir%\~TOOLS\tools.ps1 "SystemInfo"
Everything is working correctly. This is a call to the "SystemInfo" function from the tools.ps1 library. No window or font settings required!
I can specify the same line in the shortcut on the desktop. And everything will work again! No window or font settings required!
If I compile tools.exe from tools.ps1, in the batch file I must to add the instruction:
chcp 1251
%windir%\~TOOLS\tools.exe "SystemInfo"
But I can't add instruction "chcp 1251" instruction to the shortcut! How?!

Why powershell.exe, cmd.exe and the .lnk file works correctly with Ukrainian in the code, but your .exe does not?
You don't have an answer, it's obvious. But I'll wait, maybe solve the problem somehow. Thank you for your attention and do not be offended.

**Comment by MScholtes** [comment]
Hello foxdgv,

why are you so angry, do you have no friends?

Please read my answers:
pwsh.exe has its own console settings, cmd.exe has its own console settings and a console program that is started by a link or double click has its own console settings. The last one are obviously wrong on your computer.

But if you don't want help and only want to insult the world, please do not open an issue!

**Comment by foxdgv** [comment]
In such cases, I say: "I do not know yet how to solve this problem. Please wait a week, I will try to solve it or give an unequivocal answer."
This is real programming. Nobody in the West has heard of him. And we in the East are faced with this every day. It was a lot of fun to watch the discussion and advice. :-))))
Finally, try to figure it out with real programming, namely, with compiling scripts containing localized strings. For example, I can do this in my programs. This is your problem, not Microsoft's. Microsoft programs are working correctly. Understand compilation options, with additional settings designed to work with other code pages.
So far, on the websites of Ukraine, where your compiler is discussed, I, as a Powershell specialist, have to admit that it does not work and inform others about it. Think ...
:-))))))))))))))))))))))))

**Comment by foxdgv** [comment]
Good day. I have solved the problem for you. Hope to hear "thanks" this time.
Your modified C# script:

namespace Ukraine
{
  class Program
    {
        static void Main(string[] args)
        {
            System.Console.OutputEncoding = System.Text.Encoding.Unicode;
            System.Console.WriteLine("Це повідомлення є тестовим. Воно написане українською мовою.");
            System.Console.WriteLine("Other Ukrainian letters: їісщфєпрнґгь");
            System.Console.ReadKey();
        }
   }
}

Please, compile it. All works! I hope you will think about modifying your utility in this regard.

**Comment by foxdgv** [comment]
I continued my research. I added this line to the .ps1 script at the beginning:
[system.console] :: outputencoding = [system.text.encoding] :: unicode
Now the compiled .exe forms the console window correctly, the Ukrainian language is displayed in the same way as in the cmd shell.
Now you understand that I was right and you had to properly study the issue of localizing your programs? Even if I'm a bad boy twenty times, Ukrainian letters won't appear on the screen by themselves. It takes research and work, not just the ability to take offense.

**Comment by mmillar-bolis** [comment]
@foxdgv,

In short, Windows lies to you. Yes it shows you Cyrillic, but that is
not because it natively supports the glyphs; it doesn't. Only ps2exe
is showing you how the exe will run when it doesn't inherit locale and
text protocol settings from the shell AND the programmer has FAILED to
set them explicitly.

In other words, your perception is wrong; That is the problem.

Please read this answer:
https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window

Are you beginning to understand what you are missing? Here is your C#
"fix", but in Powershell:

[System.Console]::OutputEncoding = [System.Text.Encoding]::Unicode
Write-Output "Hello World"
$host.UI.RawUI.ReadKey()

As with C#, you are supposed to do the above from within your Powershell
script.

Now for your other points, OF COURSE your programs run correctly on a
system where you have installed Windows in Ukrainian, had it deploy
shortcuts from the default user in this manner, and now use those to
launch your console sessions for cmd.exe and powershell.exe. They are
supposed to work that way. OF COURSE your C# applications produce
expected results when you compile them with UTF-16 support instead of
ASCII. They are supposed to work that way. OF COURSE Ukrainian fonts
will display correctly in ASCII mode when you set the legacy font with
the codepage command (chcp). They are supposed to work that way.

The step that you missed is that you are running in Unicode mode so you
need to set LCID (if you don't want the system to assume, when you
generate the exe) AND the Unicode protocol (from within your script).
You don't NEED to be changing the Codepage if you are working in Unicode
because Codepages are a part of ASCII and are deprecated (and are
likely set by the binary section of your console shortcuts). Just set
it to 65001 and forget about 1251 which shall will die soon, along with
437.

The LCID and the Codepage are NOT the same. Please see this table:
https://ss64.com/locale.html

On ANY system where you are using a non-latin character set, you MUST
specify such settings to construct your environment and locale. This is
true of Cyrillic, Kanji, and any other character sets within Unicode. It
sounds like you have been lucky and may not realize that project
managers like Visual Studio, XCode (and apparently FoxPro, which I
thought was mostly for DBMS, and dead, but whatever) automatically do
this for developers.

Please do some more research next time. Also review these articles:

Unicode in Microsoft Windows:
https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows

Console.OutputEncoding Property:
https://docs.microsoft.com/en-us/dotnet/api/system.console.outputencoding?view=net-5.0

OutputEncoding to the Rescue:
https://devblogs.microsoft.com/powershell/outputencoding-to-the-rescue/

What is the Console Host?:
https://neonkaraoke.ru/en/uslugi/chto-takoe-host-okna-konsoli/

**Comment by MScholtes** [comment]
Hello,

I would like to take the explosiveness out of this issue now, because there have been many misunderstandings.
The issue and the solution is not that complicated.

With the initial description of @foxdgv I thought he had the trouble only with console windows opened indirectly by running a console program. So my answer went to the direction of this post: [https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8](url), maybe with codepage 1251 instead of 65001.

Fortunately @foxdg executed my sample program, so with his description I saw that the issue is my second assumption: [https://forum.tutorials7.com/1146/printing-special-characters-cyrillic-in-the-console-in-c%23](url)

I now have enough information to make an additional parameter to **PS2EXE** that enforces console output to **UTF8** in the next version, this should solve the issue.

One thing I would like to know from @foxdgv: what value is stored in the registry of your computer in _HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP_?

Greetings and stay healthy

Markus

**Comment by foxdgv** [comment]
Good day and thanks all.
For Markus:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP=866

The situation is as follows:
1.powershell.exe with .ps1 work fine without any settings and problems with Ukrainian language.
2. I keep trying with .exe compiled from .ps1.
Problems:
1) I must to add the line to the beginning of the script:
[system.console] :: outputencoding = [system.text.encoding] :: unicode
2) However, now the problems started with the utilities launched from the script. For example, I am forced to use code like this:
[system.console] :: outputencoding = [system.text.encoding] :: ascii
invoke-expression "pnputil.exe / export-driver * $ root"
Otherwise, you will not get normal output from this utility.
Other utilities that I run from the script also have problems with output - dism and sfc / scannow. They don't work like they do in the cmd shell, the output is poor, I recommend trying.
-------------
I am currently studying the materials that you provided me. Thank you.

**Comment by foxdgv** [comment]
I continued testing. I added a line to the beginning of my tools.ps1 script and compiled into tools.exe:
[System.Console] :: OutputEncoding = new-object System.Text.UTF8Encoding
Everything works fine with Ukrainian with tools.exe.
Of the problems that remain the work of commands as:
invoke-expression "sfc.exe / scannow"
In the .ps1 variant the output goes to the screen correctly, but in the .exe it does not.
I continue to study the materials.

**Comment by MScholtes** [comment]
Hello foxdgv,

I am quite perplexed. I am getting good results with:
[System.Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("UTF-8")
or
[System.Console]::OutputEncoding = [System.Text.Encoding]::Unicode
or
[System.Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("windows-1251")

with 
[System.Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("cp866")
I am getting your initial problem (I think Windows gets confused here about ukrainian or russian cyrillic)

But when using a command line tool in between then the output gets messed up. Have no idea at the moment.

Greetings

Markus

**Comment by foxdgv** [comment]
Good day. I didn't understand this line:
But when using a command line tool in between then the output gets messed up. Have no idea at the moment.

When I use this: [System.Console] :: OutputEncoding = new-object System.Text.UTF8Encoding, everything works fine with Ukrainian. My library of functions already works correctly with Ukrainian. I am already using the .exe version of this library.
Now the problem is not with localization. The output to the screen when working with utilities like "dism" or "sfc /scannow" does not work correctly in the .exe version, although everything is fine in the .ps1 version.

Thank you

**Comment by MScholtes** [comment]
Hello foxgdv,

I'm having trouble with the output of tools when simultanously trying to display ukrainin cyrillic, but this seems to be an issue of my non ukrainian Windows.

Now to your latest issue: when calling for example 
```powershell
invoke-expression "sfc /?" 
```
I receive strange output too when compiled with **PS2EXE**. The reason lies in the command **_Out-String -Stream_** that **PS2EXE** appends to all scripts. The reason why I have to do this is that the Powershell pipeline handles objects, the cmd.exe pipeline handles only strings (and this pipeline an executable uses). To not get an output of the name of the object in the pipeline I have to explicitly convert to string.

Apparently sometimes this fails, and the strings got sort of "double converted". You can see this if you execute 
```powershell
Invoke-expression "sfc /?" | Out-String -Stream
```
in **Powershell**.

The only workaround I found so far is to force conversion of the pipeline to an object before, example in **Powershell**:
```powershell
Invoke-expression "sfc /?" | Out-Default | Out-String -Stream
```

In your script you want to convert with **PS2EXE** you could use an expression like:
```powershell
Invoke-expression "sfc /?" | Out-Default
```

Greetings

Markus

**Comment by foxdgv** [comment]
Good day! The variant
invoke-expression "sfc.exe /scannow" | out-default
works in .exe normally. Thanks! You are great!
----------------------------------
There is also a similar problem.
Commands for integrating updates into a Windows image:
mount-windowsimage -imagepath <path_to_wim> -index <number> -path <path_to_image> | out-null
add-windowspackage -path <path_to_image> -packagepath <path_to packages> | out-null
dismount-windowsimage -path <path_to_image> -save | out-null
Execution is accompanied by a built-in progress indicator, which is enabled by default, but can be disabled using the value of the variable:
$ ProgressPreference = "SilentlyContinue"
In the .ps1 mode, everything works correctly, the progress indicator is shown, but in the .exe mode, it is not.

------------------------------------
I continue to test the capabilities of your utility on my functions.

**Comment by foxdgv** [comment]
This command also works normally in .exe:
invoke-expression "dism.exe /image:<my_image> /cleanup-image /startcomponentcleanup /resetbase" | out-default

**Comment by MScholtes** [comment]
Hello foxdgv,

I have not implemented **Write-Progress** in "console mode" since it would be too much work (there are no API calls I could use).

Greetings

Markus

**Comment by foxdgv** [comment]
Good day.
The progress bar is built into these commands. The command **write-progress** is not used by me directly. It can only be disabled, and you can also adjust the colors of the progress window. Even if I enable it, in the .exe version it simply does not work - it does not appear by itself.
I actually forcibly disable the progress bar in the script - due to the fact that you cannot control its position, but this is not the point. This is an auxiliary window that is blocked for some reason in the .exe version of the script, but works in .ps1. Sooner or later, this question may arise again. If you are interested, try to figure it out.

------------------------

If you like, I can provide my library of functions for you to test ((put it on Google Drive). It's small and straightforward.
Besides, I'm a pretty good Windows configuration expert. I installed my first Windows in 1993.
You said that your Windows is Western, so it works differently than mine. This is not true. There is no Ukrainian or German Windows, there is English with installed language packs. This means that I can easily switch to the English interface on my computer (it is built-in by default), change the regional formats, and at the same time all my Ukrainian scripts will work correctly. I tried.
Ask me, if you have an "eastern type" problem, suggest testing your developments. One head it's good, but two better.
I have hyper-modern software that I build bit by bit myself, I also make modern Windows distributions. Build 10.0.19042.685 Windows 10 x64 Enterprise, which is popular in Ukraine, is made by me.

**Comment by foxdgv** [comment]
Good day.
There is another option for performing this construction:
invoke-expression "sfc.exe /scannow" | out-default
-------------------------
start-process -filepath "sfc.exe" -argumentlist "/scannow" -verb RunAs -wait
------------------------
It launches a separate cmd-window and executes the command there, which looks less pretty, but it has two very big advantages: the -verb RunAs option and the -wait option. The execution of such a command goes in administrative mode and the script waits for the execution of such an external command (the invoke-expression cmdlet has problems with this).

**Comment by MScholtes** [comment]
Hello foxdgv,

I checked in the new version of **PS2EXE** today. It has the new parameter **_-UNICODEEncoding_**, which enables the output of cyrillic / urkainian characters at the console.

It took quite a long time, as I hardly have any time on the computer (due to childcare) because of the Corona crisis. I apologise for this.

Greetings

Markus

**Comment by foxdgv** [comment]
Good day. Thank you for message. I went back to using the classic .ps1 variant. Too many problems, constantly something refuses to work - then suddenly the _read-host_ cmdlet fails, then something else.
During this time, I almost everywhere switched from using the console to graphical methods of displaying data (multiline Textbox and DataGridView), and also heavily use cmdlet _start-process_.
The .exe version of the scripts interested me most of all because of the built-in administrative launch mode. It is really convenient and necessary. But ... there are too many problems with code execution. Perhaps I myself will someday make a small launcher designed only for running regular scripts in administrative mode. This will be the simplest version without bugs.
I have translated this text using google, so sorry for the quality of my english.

**Comment by MScholtes** [comment]
Closing the issue, since it has been resolved (as far as the effort allows).

**Comment by foxdgv** [comment]
Good day. New version Win-PS2EXE.exe: V1.0.10
I tried. Result:

Invoke-ps2exe : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Invoke-ps2exe -inputFile 'D:\DOWNLOADS\~Library.ps1' -STA -verbose; R ...
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-ps2exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Are you checking your program?! Errors, errors, errors, errors...

**Comment by MScholtes** [comment]
Hello,

I tested it again and had no error.
Is it possible that you mixed the script version of _PS2EXE_ - https://github.com/MScholtes/TechNet-Gallery/tree/master/PS2EXE-GUI and https://github.com/MScholtes/Win-PS2EXE - with the module version - https://github.com/MScholtes/PS2EXE -? They are not compatible (but produce the same result).

If the problem persists, please open a new issue. This one is already closed.

Regards

Markus

**Comment by foxdgv** [comment]
First: Do you understand what is the end product for the user? Why should I install libraries from nowhere for your application to start? Why did your predecessor make a simple application that didn't force the user to solve riddles and install something?
If I prepared applications for end users like this, if I piled tons of unknown things into their systems, I would not distribute a single copy of my programs. 

Second: ok, I installed all the components and compiled the script. And all problems started again, like last time. Either the program does not understand what $psscriptroot is, then there are some other errors. I sat for two hours trying to get the scripts to run, and then I just dropped it.
In the end, I took the Powershell Studio app and compiled the scripts using it. This application has such an opportunity. Almost nothing had to be changed, no incomprehensible errors, understands the state of the environment.

**Comment by MScholtes** [comment]
Please read the readme page of **PS2EXE**, section **Remarks** first:

"**_Script variables:_**
**Since PS2EXE converts a script to an executable, script related variables are not available anymore. Especially the variable $PSScriptRoot is empty. ...**"

There the situation of script variables and the procedure with them is explained, reading this and implementing this takes five minutes and not two hours.

And please do not use **PS2EXE** anymore.

Greetings

Markus

**Comment by foxdgv** [comment]
Compared to compilation with Powershell Studio, your utility is clearly inferior, unfortunately. I've tried for a long time. All the time there are problems and it is not known at what point they will once again pop up.
I think you need to test on scripts from other developers more. 
Regards :-)))

**Comment by MScholtes** [comment]
Unfortunately, I can think of nothing more to say about these baseless accusations.

- Powershell modules must be updated with **Install-Module -Force** or **Update-Module**. This has been determined by **Microsoft** and not by me
- the **$PSScriptRoot** issue has long been described - including a workaround - on the project's **Readme.md** page. Reading helps!
- of course **PS2EXE** cannot compete with a good commercial product like **Powershell Studio** (this would be bad for the producer), but it is free of charge and has an open source license!
