### ISSUE TITLE
Issue with parameters containing commas?

### ISSUE THREAD

**Issue by rubjonny** [MScholtes/PS2EXE#34]
Hello there, my first GIT post :)

So I have a PS script which takes a comma separated parameter which is then split into an array. This works fine from the command prompt but seems to fail once converted into a .exe with your handy tool? I've tried surrounding in quotes, 'quoted' the comma as per this link but no luck:
https://stackoverflow.com/questions/11990688/powershell-is-removing-comma-from-program-argument

code excerpt:
param(
    [array] $supportedbrowser,
    [Parameter(Mandatory = $true)]
    [string] $url
)

example:
webloader.ps1 -supportedbrowser chrome,edge

**Comment by MScholtes** [comment]
Hello John,

I'm sorry to say that this cannot work. **_PS2EXE_** compiles scripts to real executables, and all executables have only access to parameters of the type string! Parameters of a complex type like array can only be passed to _Commandlets_ or _PowerShell functions_.

In your case your array is implicitly converted to a string so the compiled script only gets a string containing commas as parameter. You have to convert it to an array in your script again (maybe with **_-split ","_**).

There is nothing I can do about this since this is a limitation of the shell.

Greetings

Markus

**Comment by rubjonny** [comment]
Aha that makes sense, easy fix for me anyway. thanks for getting back to me :)

**Comment by MScholtes** [comment]
Closed due to no response for several weeks
