### ISSUE TITLE
Breaks on 90% of the scripts

### ISSUE THREAD

**Issue by init5-msft** [MScholtes/PS2EXE#41]
The tools breaks almost all the time, showing the error:

```
Invoke-PS2EXE : Missing closing '}' in statement block or type definition.
At line:1 char:1
+ Invoke-PS2EXE  .\revshell.ps1 .\revshell.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Invoke-ps2exe
```

The tools was installed online using Install-Module

**Comment by MScholtes** [comment]
Hello init5-msft,

since **PS2EXE** has been classified as malware because of compiled scripts providing a network service, I have decided to abort the attempt to compile such scripts with an error.

The error message is meant to irritate script kiddies in particular, I now think this was a flawed decision. In the next version I will create a meaningful error message.

Greetings

Markus

**Comment by init5-msft** [comment]
Hello!,

I get your point, but you're kinda shooting yourself in the foot.
What would be the value of the tool if it doesn't compile most - if not all - of pentesting/offsec utilities then? :-)

**Comment by MScholtes** [comment]
If you tell me how to distinguish a pentesting tool from a hacking tool, I'll include this :smiley:

**Comment by init5-msft** [comment]
You don't! 😁 Just like anything else, the tool could be used and/or abused, that's how it is unfortunately.

**Comment by MScholtes** [comment]
Closed since no reaction for over 3 weeks
