### ISSUE TITLE
ps2exe for linux

### ISSUE THREAD

**Issue by blindvalentine** [MScholtes/PS2EXE#46]
Hey there! ps2exe has really been a pleasure to use 💯. However, the current ps2exe module does not work with Linux as it invokes "powershell" when running the cmdlets and Linux OSes use powershell core (pwsh). Are there any plans to have a version that works with Linux? :)

**Comment by MScholtes** [comment]
Hello blindvalentine,

**PS2EXE for Linux** would be great, but there is already a lack of implementation for _.Net Core_. _.Net Core_ no longer has an integrated compiler, the compiler only comes with the _SDK_. In addition, I would have to rework large parts of **PS2EXE** in order to control a _.Net Core_ compiler. At the moment I am at a loss and have no plans for _.Net Core_ or _Linux_.

Sorry for that, greetings

Markus

**Comment by blindvalentine** [comment]
Hi Markus!

No worries! The tool module has been of great help to me and I'm really grateful for it. I just wanted to use it as part of a CI/CD pipeline, which is running on a Linux machine, hence the question.  But once again, many thanks for working on this :)

**Comment by CEbbinghaus** [comment]
Can we Repoen this issue as its not resolved. Not being able to right now != it not happening and I would love to see this being implemented as it would make building on hosted runners significantly easier.

**Comment by chmaha** [comment]
Agreed. Being able to run ps2exe on Linux would be amazing.
