### ISSUE TITLE
Question - Package config.txt file within the EXE?

### ISSUE THREAD

**Issue by ansred** [MScholtes/PS2EXE#52]
Greetings,

Thanks for taking the time on making this great tool!

Question: I have a script that it depends on a txt file on the same directory to read variables.

Is it possible to package that config file somehow within the EXE, so the moment we run the exe, it extracts the file and then it reads it?

Screenshot:
![image](https://user-images.githubusercontent.com/5244872/124347426-c0c91f80-dbb2-11eb-8389-40a5b847ebcc.png)

**Comment by MScholtes** [comment]
Hello Anas,

I understand your requirement, but **PS2EXE** is designed as a pure compiler. There are no possibilities to add files because there are countless possibilities of which and how many files and where they should be written and so on.

I recommend you use an archiving tool like **7Zip** or a program to create installers (Windows provides one with **IExpress**) for your purposes.

The other possibility would be to implement this in your script. The configuration file could then be saved in a _here-string_, for example.

Greetings and sorry

Markus

**Comment by ansred** [comment]
I will check those other options.

Thanks for the advice though!
