### ISSUE TITLE
Another Exe into the exe

### ISSUE THREAD

**Issue by MetaSeb** [MScholtes/PS2EXE#53]
Hello,

Is it possible to integrate another exe into the exe?

Example: to the exe I want to attach the 7zr.exe.

Is it possible ? 

Thanks You !

**Comment by MScholtes** [comment]
Hello MetaSeb,

I understand your requirement, but PS2EXE is designed as a pure compiler. There are no possibilities to add files because there are countless possibilities of which and how many files and where they should be written and so on. The effort to support this would be too big.

I recommend you use an self extracting tool like 7Zip or a program to create installers (Windows provides one with IExpress) for your purposes.

The other possibility would be to implement this in your script. The executable could be stored in Base64 string, for example.

Greetings and sorry

Markus

**Comment by MetaSeb** [comment]
Hello, 

Thank you for the answer on the subject 👍

**Comment by MScholtes** [comment]
Closed since no action is required
