### ISSUE TITLE
Has any plan to upgrade support powershell 7?

### ISSUE THREAD

**Issue by whiter001** [MScholtes/PS2EXE#55]

**Comment by MScholtes** [comment]
Hello whiter001,

_PS2EXE_ internally calls the _.Net C#_ compiler to compile _Powershell_ scripts to executables. Since there is no compiler built in _.Net Core_ and therefore in _Powershell_ 7.x there is no way to migrate _PS2EXE_.

Sorry for that, but that (including the steady removing of _Windows_ platfom support in _Powershell Core_) is a result of _Microsofts_ decisions.

Greetings

Markus

**Comment by whiter001** [comment]
Thanks for your reply
Maybe it's just Iexpress compression
