### ISSUE TITLE
Colored Write-Host text in GUI

### ISSUE THREAD

**Issue by FD-IBKuF** [MScholtes/PS2EXE#63]
Would it be possible to allow for the output of Write-Host (or similar cmdlets) in GUI windows to be colored according to the -ForegroundColor parameter set when calling Write-Host? I often use coloring to highlight important information, a heads-up or even positive feedback/results. Having that ability in the GUI would be very useful.

EDIT: While browsing the code I've just found a part where you seem to have even prepared just such a feature:
https://github.com/MScholtes/PS2EXE/blob/40e8437e9cfd2281f9d7595ef93f68ccc0768edb/Module/ps2exe.ps1#L554-L557

**Comment by MScholtes** [comment]
Hello @FD-IBKuF,

as you correctly pointed out, I did tests with the colouring of GUI dialogues a long time ago: it looks atrocious (you can only use the console colours to remain compatible). Since this is not in line with the Windows design guidelines, for good reason, I discarded the idea.

Please use **Write-Verbose**, **Write-Warning** and **Write-Error** to mark the feedback.

Greetings

Markus

**Comment by FD-IBKuF** [comment]
Thanks for the reply, sounds like a good reason to not support the console colours.
I'll give the different Write-Variants a go and see how I can integrate them.

Thanks again!
