### ISSUE TITLE
Update version information in the module/script

### ISSUE THREAD

**Issue by kyallanum-WSS** [MScholtes/PS2EXE#65]
It is slightly confusing when downloading the Module from PSGallery and I run 'ps2exe' I see:
PS2EXE-GUI v0.5.0.26 by Ingo Karstein, reworked and GUI support by Markus Scholtes

Considering the module is now at 1.1.11 it confused me when I first used it as I thought I was using an older version.

**Comment by MScholtes** [comment]
Hello @kyallanum-WSS,

I'm sorry you find the versioning disturbing but **PS2EXE** is older then **Powershell Gallery** and was presented on the **Technet Gallery**. In respect to Ingo Karstein, who originally developed **PS2EXE** up to version 0.5.0.0, I increase only the last number of the version. Since **Technet Gallery** is closed, you now find the original _"non-module"_ version here: https://github.com/MScholtes/TechNet-Gallery

The _"module"_ version came much later and since beside the rearranged **PS2EXE** it contains the project **Win-PS2EXE** too (https://github.com/MScholtes/Win-PS2EXE), which has the actual version number 1.0.1.1, I started with a new "**Powershell Gallery**" compliant versioning for the whole module.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed for no reaction
