### ISSUE TITLE
Invoke-ps2exe errors out when trying to run

### ISSUE THREAD

**Issue by JamesIsWack** [MScholtes/PS2EXE#88]
Hello,
After installing ps2exe in Powershell 7, I always get 
`& : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable program.`

![image](https://user-images.githubusercontent.com/94473358/204149905-47a0afaa-498a-4440-8580-2e505a03655c.png)

I dont know why this happens, any help is appreciated,

James

**Comment by JamesIsWack** [comment]
I tried using the GUI from the repo too, same result.

**Comment by MScholtes** [comment]
Hello @JamesIsWack,

**PS2EXE** does not work in **Powershell 7**, since **.Net Core** contains no compiler.

You have to use the Windows PowerShell Compatibility functionality with **Import-Module PS2EXE -UseWindowsPowerShell** (see here: https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility). Maybe you have to install the module in Windows Powershell first (start _powershell.exe_ instead of _pwsh.exe_ for this).

Greetings

Markus

**Comment by JamesIsWack** [comment]
> Hello @JamesIsWack,
> 
> **PS2EXE** does not work in **Powershell 7**, since **.Net Core** contains no compiler.
> 
> You have to use the Windows PowerShell Compatibility functionality with **Import-Module PS2EXE -UseWindowsPowerShell** (see here: https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility). Maybe you have to install the module in Windows Powershell first (start _powershell.exe_ instead of _pwsh.exe_ for this).
> 
> Greetings
> 
> Markus

hey markus, this is fine since i found another way to make my PS scripts exes, im using Powershell ISE Steroids now. however it requires a license, so in 10 days i may try this xD

i used it for this: https://github.com/JamesIsWack/Simple-MSI-Extractor

**Comment by MScholtes** [comment]
This issue and the solution for it is now documented on the readme page.
