### ISSUE TITLE
Try - Catch gives error after converting to EXE

### ISSUE THREAD

**Issue by arkayali** [MScholtes/PS2EXE#91]
Hi,

I use Try/Catch to hide the error message appears when there are no users on remote servers using command: quser
and it works well when I run the PS script as is.

 
![image](https://user-images.githubusercontent.com/44178884/206539788-e7b22835-ab5b-4659-8a1f-433ba0de4a40.png)

When I converted the script to exe, I got an error as if there is no Try/Catch 

 
![image](https://user-images.githubusercontent.com/44178884/206539808-640ead85-2027-4e54-a381-7d8345b4fda5.png)

**Comment by MScholtes** [comment]
Hello @arkayali,

as much as I know **quser** generates non-terminating errors so an **try-catch** construct  would be ignored. Can you post the try-catch block you use here?

Greetings

Markus

**Comment by arkayali** [comment]
Hi @MScholtes 
![image](https://user-images.githubusercontent.com/44178884/206740399-b11f9e08-f2d8-46b0-aa64-f92bcd9a792b.png)

**Comment by MScholtes** [comment]
Hello @arkayali,

I cannot reproduce the issue. In my environment, an uncompiled script behaves the same as a script compiled with **PS2EXE**: the error message _"No user exist for *"_ is displayed which is correct to my understanding since **quser.exe** in not catchable and displays this error message when no user is logged on.

How do you start the script - with error redirection or something similiar? Which _Powershell_ version is in use?

Greetings Markus
