### ISSUE TITLE
[question] Lost parameter

### ISSUE THREAD

**Issue by scriptingstudio** [MScholtes/PS2EXE#95]
I'm sorry I have missed something. :-)) I just recently updated. There was a parameter `-runtime40`. What did it do, was it replaced or removed? 
Would it be useful to leave a stub for removed parameters (and introduce alias for replaced) which does nothing?

**Comment by MScholtes** [comment]
Hello @scriptingstudio,

there are two editions of **PS2EXE**,

- the module based edition that requires **PowershellGet** - this version. Since **PowershellGet** requires _.Net Framework 4.x_, there is no need to select a _.Net_ runtime. Therefore there is no parameter **-runtime20** or **-runtime40**.
- the script based edition that can generate executables for _.Net Framework 2.0/3.5_ and _.Net Framework 4.0_ - the original version of **PS2EXE**. There exist parameters **-runtime20** or **-runtime40** to select the target framework version. You can find this edition here in my "_former Technet-Gallery_"-Repository: https://github.com/MScholtes/TechNet-Gallery.

Greetings

Markus

**Comment by scriptingstudio** [comment]
I always used this version https://github.com/MScholtes/PS2EXE/blob/master/Module/ps2exe.ps1 and at one moment the script throwed exception. Thats why I asked.
Thanks alot.
