### ISSUE TITLE
problem with parameters that are of type list (of filenames)

### ISSUE THREAD

**Issue by mbassiouny33** [MScholtes/PS2EXE#98]
Hi

I noticed a problem with ps2exe after I compiled my ps1 to an exe

In the readme it says ". One restriction comes from the Windows environment: for all executables all parameters have the type STRING,"

My script has 
```
[Parameter(ParameterSetName="Default", mandatory=$true)][string[]]$files,
echo $files
```

In powershell, $files is an array with 2 strings
When I run the run the .exe  `script.exe -file "filename1","filename2"` what I get inside my script is now 1 long string that has <"filename1","filename2">.
Only problem is... You can't decide to split that long string on comma because `,` is valid in filenames on Windows, and I have already seen filenames with `,`. 

So if I split that string naively on comma, I may get incomplete filenames.

Example of naive splitting:
```
.\param.exe -files "lol","l,ol2"                           
lol
l
ol2
# the output should like :
.\param.ps1 -files "lol","l,ol2"
lol
l,ol2
```
How does one deal with this problem in the compiled script?

Thanks

**Comment by MScholtes** [comment]
Hello @mbassiouny33,

unfortunately, executable files and therefore also scripts compiled with **PS2EXE** have to live with the fact that parameters are only passed as strings. If you want a string array, you have to make a conversion in your script.

So I do not see where your problem is, files with a comma in their name are enclosed in quotation marks.

Greetings

Markus

**Comment by mbassiouny33** [comment]
>So I do not see where your problem is, files with a comma in their name are enclosed in quotation marks.

I am not sure I understand that part.

In the script, if you do the following

```
Param( [Parameter(mandatory=$true)][string[]]$files ) 
echo $files.Substring(0,1)
```
then Compile to exe a run with ` .\param.exe -f "lol","l,ol2" `  
This will print `l`, because the first letter is `l`, it will not print `"`  **the received string passed to the compiled script does not seem to be enclosed**, is it?

if you do  `($files.Split(',"'))`  this will return an array of 3 elements in this particular case, not 2 elements.

How would convert that back to an array of 2 strings in the script?

**Comment by MScholtes** [comment]
Hello @mbassiouny33,

I think you have to say the calling _Powershell_ that you don't want an _array_ but a _string_ with something like:
```powershell
.\param.exe -files '"lol","l,ol2"'
```
(do you see the single quotes around the last expression?)

I have no better idea because the parser of Powershell is unfortunately sometimes ambiguous, sometimes the "stop-parsing" token _--%_ helps, but not here.

Greetings

Markus

**Comment by mbassiouny33** [comment]
I get it now!

Thanks
